function(mca_mnn_cache_namespace manifest output)
    file(STRINGS "${manifest}" patch_line REGEX "^patch=")
    file(STRINGS "${manifest}" hash_line REGEX "^patchSha256=")
    string(REGEX REPLACE "^patch=" "" patch_name "${patch_line}")
    string(REGEX REPLACE "^patchSha256=" "" expected "${hash_line}")
    get_filename_component(vendor_dir "${manifest}" DIRECTORY)
    set(patch_path "${vendor_dir}/${patch_name}")
    file(READ "${patch_path}" patch_text)
    string(REPLACE "\r\n" "\n" patch_text "${patch_text}")
    string(REPLACE "\r" "\n" patch_text "${patch_text}")
    string(SHA256 actual "${patch_text}")
    if(NOT actual STREQUAL expected)
        message(FATAL_ERROR "MNN cache namespace requires the verified vendor patch")
    endif()
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${manifest}" "${patch_path}")
    set(${output} "${actual}" PARENT_SCOPE)
endfunction()
