include("${CMAKE_CURRENT_LIST_DIR}/../../../main/cpp/mnn_vendor_cache.cmake")
file(MAKE_DIRECTORY "${TEST_DIR}")
set(patch "diff one\n")
string(SHA256 expected "${patch}")
file(WRITE "${TEST_DIR}/test.patch" "diff one\r\n")
file(WRITE "${TEST_DIR}/manifest.properties" "patch=test.patch\npatchSha256=${expected}\n")
mca_mnn_cache_namespace("${TEST_DIR}/manifest.properties" actual)
if(NOT actual STREQUAL expected)
    message(FATAL_ERROR "CRLF-normalized cache namespace mismatch")
endif()
set(patch "diff two\n")
string(SHA256 updated "${patch}")
file(WRITE "${TEST_DIR}/test.patch" "${patch}")
if(NOT TAMPER)
    file(WRITE "${TEST_DIR}/manifest.properties" "patch=test.patch\npatchSha256=${updated}\n")
endif()
mca_mnn_cache_namespace("${TEST_DIR}/manifest.properties" actual)
if(actual STREQUAL expected OR NOT actual STREQUAL updated)
    message(FATAL_ERROR "Patch change did not isolate cache namespace")
endif()
